---
name: Test-XML-Deep
version: 0.01
author:
  - 'Jeff Lavallee <jeff@zeroclue.com>'
abstract: XML::Simple + Test::Deep = Test::XML::Deep
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Test::XML::Deep:
    file: lib/Test/XML/Deep.pm
    version: 0.01
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
